export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const DELETE_SEARCH_TERM = 'DELETE_SEARCH_TERM';
export const LOAD_TILES = 'LOAD_TILES';
export const EDIT_STATE = 'EDIT_STATE';
export const DISPATCH_FILTERED_TILE = 'DISPATCH_FILTERED_TILE';
export const SAVE_TILE_DATA = 'SAVE_TILE_DATA';
